Projekat/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Projekat.Models;

namespace Projekat.Controllers
{
    [Authorize(Roles = "ROwner")]
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index(int Id)
        {
            ViewBag.ResId = Id;
            //db.Menus.Where(m => m.RestaurantModels_id.Equals(Id)).ToList()
            return View(db.Menus.Where(m => m.RestaurantModels_id.Equals(Id)).ToList());
        }

        // GET: Menu/Details/5
        public ActionResult Details(int id)
        {
            var menu = new MenuModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.Menus.Find(id);
            }
            return View(menu);
        }

        public ActionResult Create(int restauarnt_id)
        {
            ViewBag.ResId = restauarnt_id;
            return View();
        }

        // POST: Menu/Create
        [HttpPost]
        public ActionResult Create(MenuModels model)
        {
            try
            {
                string user_id = User.Identity.GetUserId();
                MenuModels newM = new MenuModels
                {
                    MenuName = model.MenuName,
                    Desc = model.MenuName,
                    ApplicationUserId = User.Identity.GetUserId(),
                    RestaurantModels_id = model.RestaurantModels_id

                };
                db.Menus.Add(newM);
                db.SaveChanges();

                TempData["Message"] = $"Created Menu: {model.MenuName}";

                // TODO: Add insert logic here
                return RedirectToAction("Index", new { Id = model.RestaurantModels_id });
            }
            catch(Exception e)
            {
                return Content(e.InnerException.ToString());
            }
        }

        // GET: Menu/Edit/5
        public ActionResult Edit(int id)
        {
            var menu = new MenuModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.Menus.Find(id);
            }
            return View(menu);
        }

        // POST: Menu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MenuModels collection)
        {
            try
            {
                // TODO: Add update logic here

                var r = db.Menus.Find(id);
                collection.ApplicationUserId = User.Identity.GetUserId();
                collection.RestaurantModels_id = r.RestaurantModels_id;
                db.Entry(r).CurrentValues.SetValues(collection);
                db.SaveChanges();

                TempData["Message"] = $"You have edited restaurant: {r.MenuName}";

                return RedirectToAction("Index", new { Id = r.RestaurantModels_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                using (db = new ApplicationDbContext())
                {
                    var some = db.Menus.Find(id);
                    db.Menus.Remove(some);
                    db.SaveChanges();

                    TempData["Message"] = "It Was Deleted";

                    // TODO: Add insert logic here
                    return RedirectToAction("Index", new { Id = some.RestaurantModels_id });
                }
                
            }
            catch
            {
                return View();
            }
        }

    }
}

Projekat/Controllers/RestaurantOwnerController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Projekat.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projekat.Controllers
{
    [Authorize(Roles = "ROwner")]
    public class RestaurantOwnerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RestaurantOwner
        public ActionResult Index()
        {
            string user_ID = User.Identity.GetUserId();
            var list = db.Restaurants.Where(r => r.ApplicationUserId == user_ID).ToList();
            return View(list);
        }

        // GET: RestaurantOwner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RestaurantOwner/Create
        [HttpPost]
        public ActionResult Create(RestaurantModels model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RestaurantModels r = new RestaurantModels { Name = model.Name, Desc = model.Desc, ApplicationUserId = User.Identity.GetUserId() };
                    db.Restaurants.Add(r);
                    db.SaveChanges();

                    TempData["Message"] = $"You have created new restaurant: {model.Name}";

                    return RedirectToAction("Index");
                }
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        // GET: RestaurantOwner/Edit/5
        public ActionResult Edit(int id)
        {
            var r = db.Restaurants.Find(id);
            return View(r);
        }

        // POST: RestaurantOwner/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, RestaurantModels collection)
        {
            try
            {
                // TODO: Add update logic here
                var r = db.Restaurants.Find(id);
                collection.ApplicationUserId = User.Identity.GetUserId();
                db.Entry(r).CurrentValues.SetValues(collection);
                db.SaveChanges();

                TempData["Message"] = $"You have edited restaurant: {r.Name}";

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            return View(db.Restaurants.Find(id));
        }

        // GET: RestaurantOwner/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                var res = db.Restaurants.Find(id);
                db.Restaurants.Remove(res);
                db.SaveChanges();

                TempData["Message"] = $"You have deleted restaurant: {res.Name}";

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

Projekat/Views/RestaurantOwner/Create.cshtml
@model Projekat.Models.RestaurantModels

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RestaurantModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekat/Views/RestaurantOwner/Details.cshtml
@model Projekat.Models.RestaurantModels

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Restaurant Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index") |
    <a href="@Url.Action("Index","Menu",new { Id = Model.Id})">Menus</a>
</p>

Projekat/Views/RestaurantOwner/Edit.cshtml
@model Projekat.Models.RestaurantModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RestaurantModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekat/Views/RestaurantOwner/Index.cshtml
@model IEnumerable<Projekat.Models.RestaurantModels>

@{
    ViewBag.Title = "My Restaurants";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>

}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Name)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Desc)</th>
            <th scope="col">#Actions you can take</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Desc)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

Projekat/Views/RestaurantOwner/_RLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projekat ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @**@
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark " style="margin-bottom: 20px;">
        @Html.ActionLink("Projekat", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto" style="padding-right: 15px;">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Basic Pages
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "dropdown-item" })
                    </div>
                </li>

                @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")

            </ul>
        </div>
    </nav>
    @**@

    <div class="container body-content">

        <div class="container-fluid">
            <div class="row">
                @Html.Partial("~/Views/RestaurantOwner/_RNavbar.cshtml")

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h1 class="h2">Dashboard</h1>
                        <div class="btn-toolbar mb-2 mb-md-0">
                            <div class="btn-group mr-2">
                                <button class="btn btn-sm btn-outline-secondary">Share</button>
                                <button class="btn btn-sm btn-outline-secondary">Export</button>
                            </div>
                            <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                                <span data-feather="calendar"></span>
                                This week
                            </button>
                        </div>
                    </div>

                    <!---<canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
                    <div class="my-4 w-100">
                        @RenderBody()
                    </div>


                </main>
            </div>
        </div>
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application Dusan Kostic</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace()
    </script>
</body>
</html>

Projekat/Views/RestaurantOwner/_RNavbar.cshtml
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">

            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Index","RestaurantOwner")">
                    <span data-feather="home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Create","RestaurantOwner")">
                    <span data-feather="plus"></span>
                    Restaurants <span class="sr-only">(current)</span>
                </a>
            </li>
        </ul>
    </div>
</nav>