Projekat/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Projekat.Models;

namespace Projekat.Controllers
{
    [Authorize(Roles = "ROwner")]
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index(int Id)
        {
            ViewBag.ResId = Id;
            //db.Menus.Where(m => m.RestaurantModels_id.Equals(Id)).ToList()
            return View(db.Menus.Where(m => m.RestaurantModels_id.Equals(Id)).ToList());
        }

        // GET: Menu/Details/5
        public ActionResult Details(int id)
        {
            var menu = new MenuModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.Menus.Find(id);
            }
            return View(menu);
        }

        public ActionResult Create(int restauarnt_id)
        {
            ViewBag.ResId = restauarnt_id;
            return View();
        }

        // POST: Menu/Create
        [HttpPost]
        public ActionResult Create(MenuModels model)
        {
            try
            {
                string user_id = User.Identity.GetUserId();
                MenuModels newM = new MenuModels
                {
                    MenuName = model.MenuName,
                    Desc = model.MenuName,
                    ApplicationUserId = User.Identity.GetUserId(),
                    RestaurantModels_id = model.RestaurantModels_id

                };
                db.Menus.Add(newM);
                db.SaveChanges();

                TempData["Message"] = $"Created Menu: {model.MenuName}";

                // TODO: Add insert logic here
                return RedirectToAction("Index", new { Id = model.RestaurantModels_id });
            }
            catch(Exception e)
            {
                return Content(e.InnerException.ToString());
            }
        }

        // GET: Menu/Edit/5
        public ActionResult Edit(int id)
        {
            var menu = new MenuModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.Menus.Find(id);
            }
            return View(menu);
        }

        // POST: Menu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MenuModels collection)
        {
            try
            {
                // TODO: Add update logic here

                var r = db.Menus.Find(id);
                collection.ApplicationUserId = User.Identity.GetUserId();
                collection.RestaurantModels_id = r.RestaurantModels_id;
                db.Entry(r).CurrentValues.SetValues(collection);
                db.SaveChanges();

                TempData["Message"] = $"You have edited restaurant: {r.MenuName}";

                return RedirectToAction("Index", new { Id = r.RestaurantModels_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                using (db = new ApplicationDbContext())
                {
                    var some = db.Menus.Find(id);
                    db.Menus.Remove(some);
                    db.SaveChanges();

                    TempData["Message"] = "It Was Deleted";

                    // TODO: Add insert logic here
                    return RedirectToAction("Index", new { Id = some.RestaurantModels_id });
                }
                
            }
            catch
            {
                return View();
            }
        }

    }
}

Projekat/Controllers/MenuItemController.cs
using Microsoft.AspNet.Identity;
using Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projekat.Controllers
{
    [Authorize(Roles = "ROwner")]
    public class MenuItemController : Controller
    {
        private ApplicationDbContext db;
        // GET: MenuItem
        public ActionResult Index(int Id)
        {
            using (db = new ApplicationDbContext())
            {
                ViewBag.MenuId = Id;
                return View(db.MenuItems.Where(m => m.MenuModels_id.Equals(Id)).ToList());
            }
        }

        // GET: MenuItem/Details/5
        public ActionResult Details(int id)
        {
            var menu = new MenuItemModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.MenuItems.Find(id);
            }
            return View(menu);
        }

        // GET: MenuItem/Create
        public ActionResult Create(int menu_id)
        {
            ViewBag.MenuId = menu_id;
            return View();
        }

        // POST: MenuItem/Create
        [HttpPost]
        public ActionResult Create(MenuItemModels collection)
        {
            try
            {
                // TODO: Add insert logic here

                using (db = new ApplicationDbContext())
                {
                    MenuItemModels menu = new MenuItemModels { Name = collection.Name,
                        Desc = collection.Desc, Price = collection.Price, MenuModels_id = collection.MenuModels_id };
                    menu.ApplicationUserId = User.Identity.GetUserId();
                    menu.MenuModels_id = collection.MenuModels_id;
                    menu.RestaurantModels_id = db.Menus.Find(collection.MenuModels_id).RestaurantModels_id;
                    db.MenuItems.Add(menu);
                    db.SaveChanges();

                    TempData["Message"] = $"You have created a menu item: {menu.Name}";

                    return RedirectToAction("Index", new { Id = collection.MenuModels_id });
                }
            }
            catch(Exception e)
            {
                return Content(e.Message);
            }
        }

        // GET: MenuItem/Edit/5
        public ActionResult Edit(int id)
        {
            var menu = new MenuItemModels();
            using (db = new ApplicationDbContext())
            {
                menu = db.MenuItems.Find(id);
            }
            return View(menu);
        }

        // POST: MenuItem/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, MenuItemModels collection)
        {
            try
            {
                // TODO: Add update logic here

                using (db = new ApplicationDbContext())
                {
                    var r = db.MenuItems.Find(id);
                    collection.ApplicationUserId = User.Identity.GetUserId();
                    collection.MenuModels_id = r.MenuModels_id;
                    collection.RestaurantModels_id = r.RestaurantModels_id;
                    db.Entry(r).CurrentValues.SetValues(collection);
                    db.SaveChanges();

                    TempData["Message"] = $"You have edited restaurant: {r.Name}";

                    return RedirectToAction("Index", new { Id = collection.MenuModels_id });
                }
            }
            catch(Exception e)
            {
                return Content(e.ToString());
            }
        }

        // GET: MenuItem/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                using (db = new ApplicationDbContext())
                {
                    var some = db.MenuItems.Find(id);
                    db.MenuItems.Remove(some);
                    db.SaveChanges();

                    TempData["Message"] = "It Was Deleted";

                    // TODO: Add insert logic here
                    return RedirectToAction("Index", new { Id = some.MenuModels_id });
                }
               
            }
            catch
            {
                return View();
            }
        }

    }
}

Projekat/Views/Menu/Create.cshtml
@model Projekat.Models.MenuModels

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" name="RestaurantModels_id" value="@ViewBag.ResId" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekat/Views/Menu/Details.cshtml
@model Projekat.Models.MenuModels

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MenuModels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenuName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenuName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
    <a href="@Url.Action("Index","MenuItem",new { Id = Model.Id})">Menu Items</a>
</p>

Projekat/Views/Menu/Edit.cshtml
@model Projekat.Models.MenuModels

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MenuModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MenuName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MenuName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MenuName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekat/Views/Menu/Index.cshtml
@model IEnumerable<Projekat.Models.MenuModels>

@{
    ViewBag.Title = "Index";

}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<h2>Index</h2>


<a href="@Url.Action("Create","Menu", new {restauarnt_id = ViewBag.ResId })" class="btn btn-success mb-1">Create New Menu</a>


<table class="table table-hover table-dark ">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.MenuName)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Desc)</th>
            <th scope="col">#Actions you can take</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.MenuName)</td>
                <td>@Html.DisplayFor(modelItem => item.Desc)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>